version: '3'

services:
  db:
    image: postgres:14-alpine3.17
    networks:
      - bridge1
    container_name: db_app
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.2-alpine
    networks:
      - bridge1
    container_name: redis_app
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ./data/cache:/data

  web:
    image: nginx
    networks:
      - bridge1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "0.0.0.0:80:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - app

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bridge1
    image: app
    container_name: app_container
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:  >
      bash -c "python  manage.py collectstatic --noinput
      && python manage.py makemigrations
      && python manage.py migrate      
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  celery:
    restart: always
    build:
      context: .
    networks:
      - bridge1
    container_name: celery
    env_file:
      - .env
    command: >
      bash -c "celery -A config worker -l INFO -P eventlet"
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - app
      - redis

  celery-beat:
    container_name: celery-beat
    build: .
    networks:
      - bridge1
    command: celery -A config beat —loglevel=info
#      bash -c "celery -A config beat —loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - app
      - celery

networks:
  bridge1:
    driver: bridge
